# QCUSTOMPLOT_FOUND               - QCustomPlot library was found
# QCUSTOMPLOT_INCLUDE_DIR         - Path to QCustomPlot include dir
# QCUSTOMPLOT_LIBRARY           - List of QCustomPlot libraries


IF (QCUSTOMPLOT_INCLUDE_DIR AND QCUSTOMPLOT_LIBRARY)
	# in cache already
	SET(QCUSTOMPLOT_FOUND TRUE)
ELSE (QCUSTOMPLOT_INCLUDE_DIR AND QCUSTOMPLOT_LIBRARY)
	IF (WIN32)
		FIND_LIBRARY(QCUSTOMPLOT_LIBRARY NAMES levmar.lib)
		FIND_PATH(QCUSTOMPLOT_INCLUDE_DIR NAMES qcustomplot.h)
	ELSE(WIN32)
		FIND_LIBRARY(QCUSTOMPLOT_LIBRARY
			WIN32_DEBUG_POSTFIX d
			NAMES  qcustomplot.lib
			HINTS /usr/lib /usr/lib64
		)
		FIND_PATH(QCUSTOMPLOT_INCLUDE_DIR levmar.h
			HINTS /usr/include /usr/local/include
			PATH_SUFFIXES qcustomplot
		)
	ENDIF (WIN32)
ENDIF (QCUSTOMPLOT_INCLUDE_DIR AND QCUSTOMPLOT_LIBRARY)
